apiVersion: apps/v1
kind: Deployment
metadata:
  name: sapporo-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sapporo-web
  template:
    metadata:
      labels:
        app: sapporo-web
    spec:
      containers:
      - name: sapporo-web
        image: ghcr.io/AASCTC/sapporo-web:latest
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sapporo-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sapporo-service
  template:
    metadata:
      labels:
        app: sapporo-service
    spec:
      containers:
      - name: sapporo-wes
        image: ghcr.io/AASCTC/sapporo-service:latest
        ports:
        - containerPort: 1121

---

apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: tesk
spec:
  chart:
    repository: https://charts.example.com/
    name: my-chart
    version: 1.2.3
  values:
    someKey: someValue
